name: Linux

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish macOS 64 bits
      run: dotnet publish -c Release -r osx-x64 -o Release Luciol.Plugin/Luciol.Plugin.csproj
    - uses: actions/upload-artifact@v2
      with:
        name: OSX
        path: ./Release/Luciol.Plugin.dll
        retention-days: 1
